### ISSUE TITLE
json: Unmarshal(non-pointer config.Config)

### ISSUE THREAD

**Issue by kevkha** [briandowns/raceway#18]
Looks like we have an issue in `config/config.go`. Were you able to run on your env?

``` bash
myhost:~/gocode/raceway # ./raceway -config config.json
2016/03/04 14:38:28 json: Unmarshal(non-pointer config.Config)
```

**Comment by briandowns** [comment]
You might have to figure this one out. Not gonna be near a computer for awhile.

**Comment by briandowns** [comment]
Resolved in #19

**Comment by kevkha** [comment]
Unfortunately, I still get the same error with your fix #19.

**Comment by briandowns** [comment]
I see you've merged in from my master branch but also make sure you've pulled down from yours then.

➜  raceway git:(master) ✗ make build
go get -v .
github.com/briandowns/raceway/config
github.com/briandowns/raceway/database
github.com/briandowns/raceway/scheduler
github.com/briandowns/raceway/controllers
github.com/briandowns/raceway
go build -v
github.com/briandowns/raceway

``` sh
➜  raceway git:(master) ✗ ./raceway -config config.json
2016/03/09 15:44:48 &{Raceway:{AppPort::9999 AppDebug:true} Database:{DBHost:127.0.0.1 DBPort:3307 DBUser:rally DBPass:rally DBName:rally DBDebug:true} Scenarios:{ScenarioDir:/Users/bdowns/gocode/src/gitlab.internal.tinyprints.com/bdowns/raceway/scenarios ScenarioFormat:json} Graphite:{GraphiteHost:} Scheduler:{SchedulerDBBucket:iops SchedulerDBName:raceway_scheduler.db SchedulerDBTimeout:4} HTMLOutputDir:html}
```

**Comment by kevkha** [comment]
Yes, I did the pull to my local repo. I also tried a clone from your repo and same error. Let me try to delete the `src` folder and try again.

**Comment by kevkha** [comment]
Now I jump back to my repo and did a fresh clone and `make build` fails with

``` bash
**** omitted ****
# github.com/briandowns/raceway/database
../src/github.com/briandowns/raceway/database/database.go:37: cannot use &db (type **gorm.DB) as type *gorm.DB in assignment
**** omitted ****
Makefile:26: recipe for target 'dep' failed
make: *** [dep] Error 2
```

**Comment by briandowns** [comment]
Delete all source code you have for this project locally and just clone my repo and build it and see what happens.

**Comment by kevkha** [comment]
Same error. I deleted both pkg and src folders and raceway repo folder. Did a clone of yours.

**Comment by kevkha** [comment]
#21 fixed the previous error. Now with new error

``` bash
go build -v
main.go:18:2: cannot find package "github.com/briandowns/raceway/config" in any of:
        /usr/lib64/go/src/github.com/briandowns/raceway/config (from $GOROOT)
        /root/gocode/src/github.com/briandowns/raceway/config (from $GOPATH)
main.go:19:2: cannot find package "github.com/briandowns/raceway/controllers" in any of:
        /usr/lib64/go/src/github.com/briandowns/raceway/controllers (from $GOROOT)
        /root/gocode/src/github.com/briandowns/raceway/controllers (from $GOPATH)
main.go:20:2: cannot find package "github.com/briandowns/raceway/scheduler" in any of:
        /usr/lib64/go/src/github.com/briandowns/raceway/scheduler (from $GOROOT)
        /root/gocode/src/github.com/briandowns/raceway/scheduler (from $GOPATH)
Makefile:46: recipe for target 'build' failed
make: *** [build] Error 1
```

``` bash
# go env
GOARCH="amd64"
GOBIN="/root/gocode/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gocode"
GORACE=""
GOROOT="/usr/lib64/go"
GOTOOLDIR="/usr/lib64/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by kevkha** [comment]
I had to change `import` to relative paths in all `*.go` files to get rid of the above errors.
Ex for `main.go`

``` bash
        "./config"
        "./controllers"
        "./scheduler"
```

However, I am back to database error

``` bash
go build -v
_/root/gocode/raceway/config
_/root/gocode/raceway/database
# _/root/gocode/raceway/database
database/database.go:37: cannot use &db (type **gorm.DB) as type *gorm.DB in assignment
Makefile:46: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by kevkha** [comment]
I fixed it by changing in `database.go` line 37 to `d.Conn = db`
I will update and create PR for all changes.

**Comment by briandowns** [comment]
That's bad practice and cannot be merged into the master branch. Something else will have to be figured out instead.

**Comment by kevkha** [comment]
Hmm. Ok I will check again.
Will you merge your `db_ref` branch soon?

**Comment by briandowns** [comment]
Please find my email on the page or on my website shoot me an email so we can start discussing in more detail reasoning direction expectations please

**Comment by kevkha** [comment]
Sent. Thanks Brian.

**Comment by kevkha** [comment]
Ok about the path issue the solutions is to:

``` bash
mkdir -p gocode/src/github.com/briandowns
cd gocode/src/github.com/briandowns
git clone https://github.com/briandowns/raceway.git
```

where `GOPATH` is set to `/root/gocode` so make sure to update that accordingly in your environment.
This puts a rest to this issue. We should document it in readme.

**Comment by briandowns** [comment]
Sorry I thought that's what you were doing something similar in that regard that would take care of that issue I was I would've mentioned it sooner

**Comment by kevkha** [comment]
No worries. I did in #2 but scratched it due to some conflicts. I will add some useful guides back including the new ones.
